name       : w3m
version    : 0.5.3.20161120
release    : 5
source     :
    - https://github.com/tats/w3m/archive/v0.5.3+git20161120.tar.gz : 62a5b066aaf5e23afec6decd962b966f333352150f8072193cba98320676f060
license    : MIT
component  : network.web.browser
summary    : w3m is a pager with WWW capability
description: |
    w3m is a pager with WWW capability
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(imlib2)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    sed -i 's/file_handle/file_foo/' istream.{c,h}
    %configure --libexecdir=/usr/lib64 \
               --with-imagelib=imlib2 \
               --with-termlib=ncurses
build      : |
    %make -j1
install    : |
    %make_install
