name       : w3m
version    : 0.5.3.20200502
release    : 8
source     :
    - https://github.com/tats/w3m/archive/v0.5.3+git20200502.tar.gz : bfc3d076be414b76352fa487d67b0b2aa9e400aafe684e2eb66d668a1597141c
license    : MIT
component  : network.web.browser
summary    : w3m is a pager with WWW capability
description: |
    w3m is a pager with WWW capability
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(harfbuzz)
    - pkgconfig(imlib2)
    - pkgconfig(xext)
setup      : |
    sed -i 's/file_handle/file_foo/' istream.{c,h}
    %configure --libexecdir=/usr/lib64 \
               --sysconfdir=/etc \
               --with-imagelib=imlib2 \
               --with-termlib=ncurses
build      : |
    %make -j1
install    : |
    %make_install
    install -Dm 00644 doc/keymap.default $installdir/etc/w3m/keymap
    install -Dm 00644 doc/menu.default $installdir/etc/w3m/menu
