name       : w3m
version    : 0.5.3
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/w3m/w3m/w3m-0.5.3/w3m-0.5.3.tar.gz : e994d263f2fd2c22febfbe45103526e00145a7674a0fda79c822b97c2770a9e3
license    : MIT
component  : network.web.browser
summary    : w3m is a pager with WWW capability
description: |
    w3m is a pager with WWW capability
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(imlib2)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/gc.patch
    sed -i 's/file_handle/file_foo/' istream.{c,h}
    %configure --with-imagelib=imlib2 --with-termlib=ncurses
build      : |
    %make
install    : |
    %make_install
